---
- name: Install global apt packages
  become: true
  ansible.builtin.apt:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ apt_packages }}"

- name: Remove unneeded dependencies (xfce4 cleanup)
  become: true
  ansible.builtin.apt:
    autoremove: true
