---
- name: Configure mate terminal
  become: true
  become_user: "{{ user_name }}"
  community.general.dconf:
    key: "/org/mate/terminal/profiles/default/{{ item.name }}"
    value: "{{ item.value }}"
    state: present
  with_items: "{{ dconf_values }}"
